- hosts: all
  gather_facts: true
  become: true

  tasks:
    - block:
      - shell: "vmstat 1 10 | while read line; do  echo  `date` $line  ; done"
  
      - shell: "df -h"
  
      - shell: "free -m"

      - shell: "ip a | grep inet"
